version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore: "
    # reviewers:
    #   - "your-team-name"
    # open-pull-requests-limit: 10 
    # rebase-strategy: "disabled"